Tela Detalhes
monicadaros/warrenapi pull request #1
Opened 2022-07-26 14:00 UTC by monicadaros

Criada tela detalhes com rota a partir da Tela Carteira, na screen está incluso informações e um gráfico com os valores da crypto moeda de acordo com dados recebidos da API.
A tela inclui um botão para mudança de estilo de gráfico e 4 botões com filtro de dias.

![image](https://user-images.githubusercontent.com/103940293/181023968-fd5e4c04-1a5e-4122-ba1c-7619f2f8a9af.png)

2022-07-26 14:06 UTC, carlosWarren requested changes
So remover aquela linha

2022-07-26 14:06 UTC, carlosWarren commented on lib/usecase/usecase.dart
> +    await Future.delayed(const Duration(seconds: 2));
Pode remover essa linha

2022-07-26 15:00 UTC, monicadaros commented on lib/usecase/usecase.dart
> +    await Future.delayed(const Duration(seconds: 2));
Linha 19 apagada.

2022-07-26 18:51 UTC, BrunoSabadini commented on lib/lists/button_charts_list.dart
> +    ChartModel(buttonName: 30),
Acho que falta só o botão de 50.

2022-07-26 18:58 UTC, BrunoSabadini approved these changes

2022-07-26 18:59 UTC, monicadaros commented on lib/lists/button_charts_list.dart
> +    ChartModel(buttonName: 30),
A API só tem 30 dados.

2022-07-26 22:44 UTC, BrunoSabadini commented on lib/lists/button_charts_list.dart
> +    ChartModel(buttonName: 30),
Aaa, showw!

2022-07-27 14:36 UTC, merged

2022-07-27 19:21 UTC, mauriciwarren reviewed
OK